server:
  port: 8000
dubbo:
  scan:
    base-packages: com.zx.dbo.provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://192.168.13.146
spring:
  application:
    name: SprProvider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.13.146:8848
  main:
    allow-bean-definition-overriding: true
